### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by chibicatt2** [chibicatt2/protospace-39125#1]
＃URL
https://protospace-39125.onrender.com

**Comment by shodai-ito** [comment]
@chibicatt2 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by chibicatt2** [comment]
@shodai-ito 
ご確認ありがとうございます！！
一発でLGTMをいただけて嬉しいです🙌🏻　モチベーションが上がりました⤴️
最終課題もこの調子で取り組んでいきます✊🏻
